[package]
name = "day24"
version = "0.1.0"
authors = ["Hal Massey <harrison.massey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"point_2d" = { path = "../point_2d" }
"regex" = "^1.4.2"
