[package]
name = "day09"
version = "0.1.0"
authors = ["Hal Massey <harrison.massey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"weak-table" = "^0.3.0"
